### ISSUE TITLE
Only run CI checks on commits to master when certain files are modified

### ISSUE THREAD

**Issue by bitcoin-tools** [bitcoin-tools/nodebuilder#404]
```
  push:
    branches: [ master ]
    paths:
      - Dockerfile
      - dependencies.txt
      - nodebuilder
      - test/test_bitcoin
      - .github/workflows/*.yaml
      - dockerfiles/Dockerfile_*
```
