### ISSUE TITLE
[FEAT] If test_nodebuilder fails in CI, run nodebuilder in -x mode

### ISSUE THREAD

**Issue by bitcoin-tools** [bitcoin-tools/nodebuilder#707]
**Describe the problem you're having**

This might require a bit of a refactor. Maybe turn the matrix.binary-path variable into a boolean about whether to compile or not.

```
steps:
  - name: Run ${{ matrix.binary-path }}
    id: run_test
    run: /bin/sh -x ./test/test_nodebuilder
    timeout-minutes: 120
    continue-on-error: true

  - name: Follow-up step
    if: steps.run_test.outcome == 'failure'
    run: /bin/sh -x ./nodebuilder
```

**Describe the solution you'd like to see**

**Describe any alternatives you've considered**

**Additional context**
